### ISSUE TITLE
Extracting the mesh

### ISSUE THREAD

**Issue by martintseng** [StandardCyborg/StandardCyborgCocoa#25] opened 2022-06-28 15:07 UTC
I am trying to export the 3d model as a OBJ file. Within the ViewController, I am using: scenePreviewVC!.scenePreviewVC!.scScene.mesh.writeToOBJZip(atPath: filePath), but it gives me a file that does not work.

However, exporting the point clouds work, by using: scenePreviewVC!.scScene..pointCloud?.writeToPLY(atPath: filePath).

However, I am not sure if I am using the correct method. If not, can you please tell me what would be the best way to extract the mesh into an OBJ file?

**Comment by inubushi** [comment] 2022-07-25 13:04
I am trying to read the created GLTF files using other applications, but it does not seem to work. Is there any limitation as to which applications can open the GLTF files?

**Comment by pressanykeyplease** [comment] 2023-08-13 13:08
> I am trying to export the 3d model as a OBJ file. Within the ViewController, I am using: scenePreviewVC!.scenePreviewVC!.scScene.mesh.writeToOBJZip(atPath: filePath), but it gives me a file that does not work.
> 
> However, exporting the point clouds work, by using: scenePreviewVC!.scScene..pointCloud?.writeToPLY(atPath: filePath).
> 
> However, I am not sure if I am using the correct method. If not, can you please tell me what would be the best way to extract the mesh into an OBJ file?

Hey @martintseng I am facing exact the same issue. Have you figured it out?

**Comment by martintseng** [comment] 2023-08-15 01:57
Hey, they have not yet fixed the method yet, so you cannot use it.

Best,

Martin

**Comment by aaptho** [comment] 2023-08-27 04:59
Hello @martintseng, does the mesh work if you export to PLY instead of OBJ? It’s possible there’s a bug in OBJ export.
Can you provide more detail about what doesn’t work with OBJ export?

**Comment by martintseng** [comment] 2023-08-27 17:08
Unfortunately, i dont have the details. I asked Standard Cyborg if they
were  going to fix it and they asked me to create an issue in github. i
believe you can do the same and if enough people wants that function to be
working, they will fix it.

Also, i think the whole method is bugged as its incomplete so you cannot
fix it…

**Comment by pressanykeyplease** [comment] 2023-08-27 18:08
> Hello @martintseng, does the mesh work if you export to PLY instead of OBJ? It’s possible there’s a bug in OBJ export.
> Can you provide more detail about what doesn’t work with OBJ export?

Hi @aaptho thanks for reaching out! I am using a default UI from the example in the code. Here's how I save the file:

```
var objURL = documentsURL.appendingPathComponent("sample.obj")
scene.pointCloud?.writeToOBJ(atPath: objURL.path)
```

Exported OBJ file is empty - you can check an [example file here](https://drive.google.com/file/d/16gr_VJhU6yVKb2uT-Yf6VOXU9n4t_GGq/view?usp=sharing).

However, seems like `writeToUSDZ` method works good, but I cannot use it because it is not a surface, but a collection of points. Please help

**Comment by pressanykeyplease** [comment] 2023-08-28 18:26
Hey @aaptho how do you think, will this be fixed in the foreseeable future?

**Comment by aaptho** [comment] 2023-10-07 04:44
The exported OBJ file you linked looks corrupted, not at all like any OBJ file this framework writes. You might want to run with address sanitizer or zombies enabled to verify nothing in your app’s memory has been corrupted.

If you want to export a mesh, first use SCMeshingOperation to generate a mesh, then write that result to PLY. `writeToGLBAtPath` might work for you too if you can use a GLB file, it’s worth a shot.

**Comment by aaptho** [comment] 2024-05-21 03:34
It sounds like the core issue here is GLTF export not working. That is tracked by https://github.com/StandardCyborg/StandardCyborgCocoa/issues/28
I’m not sure why OBJ did not work for you both, but if you’re still able to reproduce, please comment with further detail and steps.

**Closed as completed by aaptho** 2024-05-21 03:34 UTC
